// @ts-check

export const CHARACTER_CLASSES = Object.freeze({
  ranger: {
    id: "ranger",
    label: "Ranger",
    shortLabel: "RNG",
    role: "Ranged poke / AoE pressure",
    difficulty: 2,
    color: "#3e8f9a",
    summary: "Balanced ranged scout that chips enemies down, clears camps safely, and controls space with area damage.",
    strengths: ["Long range pressure", "Reliable camp clear", "Safe objective poke"],
    weaknesses: ["Moderate durability", "Limited hard engage", "Needs aim discipline"],
    tags: ["Ranged", "Poke", "AoE"],
    stats: {
      health: 140,
      moveSpeed: 252,
      damageBonus: 0,
      defense: 0.04,
      range: 5,
      mobility: 3,
      utility: 2,
      baseSupport: 2
    },
    bars: { Health: 3, Damage: 3, Range: 5, Mobility: 3, Defense: 2, Utility: 2, "Base Support": 2, Difficulty: 2 },
    abilities: {
      basic: {
        id: "basic",
        label: "Basic Shot",
        input: "Mouse 1",
        type: "projectile",
        cooldown: 0.42,
        damage: 13,
        range: 520,
        speed: 760,
        radius: 5,
        color: "#f1d06b",
        description: "Fires a quick ranged projectile toward the cursor."
      },
      skillshot: {
        id: "skillshot",
        label: "Piercing Line",
        input: "Q",
        type: "projectile",
        cooldown: 2.8,
        damage: 32,
        range: 760,
        speed: 860,
        radius: 7,
        color: "#6ec7d6",
        pierce: true,
        description: "Fires a piercing skill shot that can pass through enemies."
      },
      area: {
        id: "area",
        label: "Anchor Field",
        input: "E",
        type: "area",
        cooldown: 6.5,
        damage: 24,
        range: 360,
        radius: 122,
        duration: 0.35,
        color: "#b391f0",
        description: "Creates a damage field at the target location."
      },
      ultimate: {
        id: "ultimate",
        label: "Corebreaker",
        input: "R",
        type: "area",
        cooldown: 34,
        damage: 105,
        range: 680,
        radius: 210,
        duration: 0.75,
        color: "#ffcf5a",
        description: "Drops a larger, high-damage area blast for fights and base raids."
      }
    }
  },
  guardian: {
    id: "guardian",
    label: "Guardian",
    shortLabel: "GRD",
    role: "Tank / melee engager / base raider",
    difficulty: 3,
    color: "#8aa0b8",
    summary: "Durable front-line fighter that survives pressure, breaks walls, and disrupts enemies up close.",
    strengths: ["High health and defense", "Strong structure pressure", "Disruptive engage"],
    weaknesses: ["Short range", "Predictable after charge", "Lower sustained ranged damage"],
    tags: ["Tank", "Melee", "Raider"],
    stats: {
      health: 220,
      moveSpeed: 224,
      damageBonus: 5,
      defense: 0.16,
      range: 1,
      mobility: 2,
      utility: 3,
      baseSupport: 3
    },
    bars: { Health: 5, Damage: 3, Range: 1, Mobility: 2, Defense: 5, Utility: 3, "Base Support": 3, Difficulty: 3 },
    abilities: {
      basic: {
        id: "basic",
        label: "Shield Bash",
        input: "Mouse 1",
        type: "melee",
        cooldown: 0.62,
        damage: 21,
        range: 88,
        radius: 44,
        color: "#d8c59a",
        structureMultiplier: 1.15,
        description: "A short melee bash that hits enemies directly in front of you."
      },
      skillshot: {
        id: "skillshot",
        label: "Shield Charge",
        input: "Q",
        type: "dash",
        cooldown: 7.4,
        damage: 34,
        range: 310,
        radius: 54,
        color: "#8aa0b8",
        status: { stun: 0.45, knockback: 78 },
        impactRadius: 118,
        impactDamageMultiplier: 0.75,
        impactColor: "#d8c59a",
        structureMultiplier: 1.25,
        description: "Dash forward, damage enemies in the path, and briefly stun or knock them back."
      },
      area: {
        id: "area",
        label: "Guard Stance",
        input: "E",
        type: "selfBuff",
        cooldown: 10,
        damage: 0,
        range: 0,
        radius: 120,
        duration: 3.2,
        color: "#72d8e8",
        damageReduction: 0.48,
        towerReduction: 0.35,
        shieldBase: 80,
        shieldPerLevel: 13,
        shieldPerAbilityLevel: 34,
        description: "Raise your shield, reducing incoming damage and tower pressure for a short time."
      },
      ultimate: {
        id: "ultimate",
        label: "Earthbreaker Slam",
        input: "R",
        type: "selfArea",
        cooldown: 38,
        damage: 84,
        range: 0,
        radius: 190,
        duration: 0.5,
        color: "#c89f5a",
        status: { slow: 0.45, duration: 2.2 },
        structureMultiplier: 2.1,
        description: "Slam around yourself, slowing enemies and dealing bonus damage to walls, towers, and cores."
      }
    }
  },
  engineer: {
    id: "engineer",
    label: "Engineer",
    shortLabel: "ENG",
    role: "Base support / traps / repairs",
    difficulty: 3,
    color: "#d49a4a",
    summary: "Utility builder that controls areas with temporary defenses and keeps structures alive.",
    strengths: ["Repairs buildings", "Temporary turret pressure", "Excellent base defense"],
    weaknesses: ["Weaker direct duels", "Needs setup time", "Lower burst damage"],
    tags: ["Utility", "Builder", "Defense"],
    stats: {
      health: 160,
      moveSpeed: 238,
      damageBonus: -2,
      defense: 0.06,
      range: 3,
      mobility: 2,
      utility: 5,
      baseSupport: 5
    },
    bars: { Health: 3, Damage: 2, Range: 3, Mobility: 2, Defense: 3, Utility: 5, "Base Support": 5, Difficulty: 3 },
    abilities: {
      basic: {
        id: "basic",
        label: "Bolt Launcher",
        input: "Mouse 1",
        type: "projectile",
        cooldown: 0.56,
        damage: 12,
        range: 455,
        speed: 690,
        radius: 6,
        color: "#e7bd58",
        description: "Fires a medium-range mechanical bolt."
      },
      skillshot: {
        id: "skillshot",
        label: "Deploy Mini Turret",
        input: "Q",
        type: "turret",
        cooldown: 11,
        damage: 10,
        range: 420,
        radius: 24,
        duration: 14,
        color: "#ffb26a",
        cooldownReductionPerLevel: 0.9,
        minCooldown: 6.8,
        turretHealthBase: 92,
        turretHealthPerLevel: 15,
        turretHealthPerAbilityLevel: 28,
        turretDamageScale: 0.74,
        description: "Places a temporary turret that attacks nearby mobs and rivals."
      },
      area: {
        id: "area",
        label: "Repair Field",
        input: "E",
        type: "repairField",
        cooldown: 12,
        damage: 0,
        range: 360,
        radius: 170,
        duration: 5,
        color: "#63d46b",
        repairPerSecond: 26,
        repairPerLevel: 1.8,
        repairPerAbilityLevel: 7,
        description: "Creates a field that repairs friendly structures and lightly heals the Engineer."
      },
      ultimate: {
        id: "ultimate",
        label: "Overclock Defense",
        input: "R",
        type: "overclock",
        cooldown: 42,
        damage: 0,
        range: 520,
        radius: 420,
        duration: 8,
        color: "#f0c85d",
        description: "Empowers nearby friendly defenses with faster firing, extra damage, and a repair pulse."
      }
    }
  },
  shadowblade: {
    id: "shadowblade",
    label: "Shadowblade",
    shortLabel: "SHD",
    role: "Assassin / stealth burst / ambush",
    difficulty: 4,
    color: "#7c63c7",
    summary: "Fragile hunter that uses fog, stealth, and burst windows to punish isolated targets.",
    strengths: ["High mobility", "Burst damage", "Stealth escapes"],
    weaknesses: ["Low health", "Poor extended fights", "Punished hard when caught"],
    tags: ["Assassin", "Stealth", "Burst"],
    stats: {
      health: 115,
      moveSpeed: 282,
      damageBonus: 8,
      defense: 0,
      range: 1,
      mobility: 5,
      utility: 3,
      baseSupport: 1
    },
    bars: { Health: 2, Damage: 5, Range: 1, Mobility: 5, Defense: 1, Utility: 3, "Base Support": 1, Difficulty: 4 },
    abilities: {
      basic: {
        id: "basic",
        label: "Twin Slash",
        input: "Mouse 1",
        type: "melee",
        cooldown: 0.38,
        damage: 17,
        range: 78,
        radius: 40,
        color: "#b391f0",
        stealthBonusMultiplier: 1.7,
        description: "Fast dagger slash. Deals bonus damage when breaking Vanish."
      },
      skillshot: {
        id: "skillshot",
        label: "Shadow Dash",
        input: "Q",
        type: "dash",
        cooldown: 5.2,
        damage: 30,
        range: 285,
        radius: 46,
        color: "#b391f0",
        description: "Dash toward the cursor, damaging enemies you pass through."
      },
      area: {
        id: "area",
        label: "Vanish",
        input: "E",
        type: "stealth",
        cooldown: 12.5,
        damage: 0,
        range: 0,
        radius: 0,
        duration: 3.2,
        color: "#7c63c7",
        untargetableKinds: ["mob", "tower", "objective", "ai"],
        breakOnDamageAction: true,
        description: "Become semi-invisible and untargetable by mobs and towers until you attack or time expires."
      },
      ultimate: {
        id: "ultimate",
        label: "Execution Mark",
        input: "R",
        type: "execute",
        cooldown: 40,
        damage: 92,
        range: 420,
        radius: 90,
        color: "#ff6b8f",
        description: "Lunge at a nearby target and deal heavy burst damage, increased against low-health enemies."
      }
    }
  },
  arcanist: {
    id: "arcanist",
    label: "Arcanist",
    shortLabel: "ARC",
    role: "Magic AoE / crowd control / zoning",
    difficulty: 4,
    color: "#5fabc1",
    summary: "Control mage that shapes objective fights with slows, ground fire, and delayed meteor bursts.",
    strengths: ["Large area control", "Strong objective fights", "Crowd control"],
    weaknesses: ["Longer cooldowns", "Lower durability", "Punishable if abilities miss"],
    tags: ["Mage", "Control", "AoE"],
    stats: {
      health: 125,
      moveSpeed: 236,
      damageBonus: 6,
      defense: 0.02,
      range: 4,
      mobility: 2,
      utility: 4,
      baseSupport: 2
    },
    bars: { Health: 2, Damage: 4, Range: 4, Mobility: 2, Defense: 1, Utility: 4, "Base Support": 2, Difficulty: 4 },
    abilities: {
      basic: {
        id: "basic",
        label: "Arcane Bolt",
        input: "Mouse 1",
        type: "projectile",
        cooldown: 0.68,
        damage: 18,
        range: 540,
        speed: 620,
        radius: 7,
        color: "#72d8e8",
        description: "Fires a slower but heavier magic projectile."
      },
      skillshot: {
        id: "skillshot",
        label: "Frost Lance",
        input: "Q",
        type: "projectile",
        cooldown: 4.4,
        damage: 34,
        range: 760,
        speed: 780,
        radius: 8,
        color: "#9ee7ff",
        pierce: true,
        status: { slow: 0.42, duration: 2.1 },
        description: "Line skill shot that damages and slows enemies briefly."
      },
      area: {
        id: "area",
        label: "Flame Wall",
        input: "E",
        type: "flameWall",
        cooldown: 9.2,
        damage: 22,
        range: 520,
        radius: 28,
        wallLength: 430,
        wallWidth: 58,
        duration: 3.6,
        tickRate: 0.55,
        color: "#ff8a5a",
        status: { slow: 0.34, duration: 1.15 },
        description: "Creates a lingering line of fire for bridge, entrance, and objective control."
      },
      ultimate: {
        id: "ultimate",
        label: "Meteor Storm",
        input: "R",
        type: "meteor",
        cooldown: 48,
        damage: 78,
        range: 760,
        radius: 260,
        duration: 1.15,
        color: "#ffcf5a",
        description: "Telegraphs a large target area, then drops several heavy AoE impacts."
      }
    }
  },
  berserker: {
    id: "berserker",
    label: "Berserker",
    shortLabel: "BRK",
    role: "Sustained melee / self-healing brawler",
    difficulty: 3,
    color: "#b84e3f",
    summary: "Aggressive bruiser that builds rage in long fights, heals on kills, and punishes enemies who stay close.",
    strengths: ["High sustained melee damage", "Kill-based sustain", "Strong camp brawling"],
    weaknesses: ["Low range", "Can be kited", "Risky defensive tools"],
    tags: ["Melee", "Bruiser", "Sustain"],
    stats: {
      health: 195,
      moveSpeed: 244,
      damageBonus: 8,
      defense: 0.08,
      range: 1,
      mobility: 3,
      utility: 2,
      baseSupport: 1,
      objectiveControl: 3
    },
    bars: { Health: 4, Damage: 5, Range: 1, Mobility: 3, Defense: 3, Utility: 2, "Base Support": 1, "Objective Control": 3, Difficulty: 3 },
    abilities: {
      basic: {
        id: "basic",
        label: "Cleaver Strike",
        input: "Mouse 1",
        type: "melee",
        cooldown: 0.56,
        damage: 24,
        range: 92,
        radius: 48,
        color: "#e85b58",
        structureMultiplier: 1.08,
        description: "Heavy short-range cleaver swing in front of you."
      },
      skillshot: {
        id: "skillshot",
        label: "Blood Hook",
        input: "Q",
        type: "projectile",
        cooldown: 7.2,
        damage: 28,
        range: 460,
        speed: 720,
        radius: 8,
        color: "#b84e3f",
        status: { slow: 0.38, duration: 1.25, knockback: -92 },
        description: "Throws a chain that damages and yanks the first enemy slightly toward you."
      },
      area: {
        id: "area",
        label: "Frenzy",
        input: "E",
        type: "selfBuff",
        cooldown: 13,
        damage: 0,
        range: 0,
        radius: 96,
        duration: 4.2,
        color: "#ff8068",
        damageReduction: 0,
        towerReduction: 0,
        speedMultiplier: 1.18,
        damageTakenMultiplier: 1.08,
        description: "Gain movement and attack tempo for a short time, but take slightly more damage."
      },
      ultimate: {
        id: "ultimate",
        label: "Bloodstorm",
        input: "R",
        type: "selfArea",
        cooldown: 42,
        damage: 52,
        range: 0,
        radius: 176,
        duration: 1.8,
        tickRate: 0.42,
        color: "#e85b58",
        description: "Spin in a bloody storm, damaging nearby enemies repeatedly."
      }
    }
  },
  druid: {
    id: "druid",
    label: "Druid",
    shortLabel: "DRU",
    role: "Sustain / control / objective support",
    difficulty: 3,
    color: "#5aa05a",
    summary: "Nature caster that sustains through fights, controls objectives, and summons an ent to hold ground.",
    strengths: ["Healing zones", "Objective control", "Flexible support"],
    weaknesses: ["Lower burst", "Needs space to set up", "Less direct base pressure"],
    tags: ["Support", "Control", "Summon"],
    stats: {
      health: 155,
      moveSpeed: 242,
      damageBonus: 2,
      defense: 0.06,
      range: 3,
      mobility: 3,
      utility: 5,
      baseSupport: 3,
      objectiveControl: 5
    },
    bars: { Health: 3, Damage: 3, Range: 3, Mobility: 3, Defense: 3, Utility: 5, "Base Support": 3, "Objective Control": 5, Difficulty: 3 },
    abilities: {
      basic: {
        id: "basic",
        label: "Nature Bolt",
        input: "Mouse 1",
        type: "projectile",
        cooldown: 0.62,
        damage: 15,
        range: 500,
        speed: 660,
        radius: 7,
        color: "#63d46b",
        description: "Fires a medium-range nature projectile."
      },
      skillshot: {
        id: "skillshot",
        label: "Root Snare",
        input: "Q",
        type: "area",
        cooldown: 6.6,
        damage: 25,
        range: 520,
        radius: 82,
        duration: 0.2,
        color: "#8ccc73",
        status: { slow: 0.7, duration: 1.55, stun: 0.32 },
        description: "Roots and damages enemies in a small ground burst."
      },
      area: {
        id: "area",
        label: "Healing Grove",
        input: "E",
        type: "repairField",
        cooldown: 13,
        damage: 0,
        range: 380,
        radius: 162,
        duration: 5.5,
        color: "#63d46b",
        repairPerSecond: 9,
        healPerSecond: 18,
        description: "Creates a healing grove. It heals allies well and repairs structures lightly."
      },
      ultimate: {
        id: "ultimate",
        label: "Ancient Ent",
        input: "R",
        type: "summon",
        cooldown: 45,
        damage: 22,
        range: 460,
        radius: 30,
        duration: 18,
        summonKind: "ent",
        summonHealth: 240,
        color: "#4f8d3f",
        description: "Summons a temporary ent guardian that attacks nearby enemies and helps hold objectives."
      }
    }
  },
  sentinel: {
    id: "sentinel",
    label: "Sentinel",
    shortLabel: "SEN",
    role: "Mid-range control / anti-melee defender",
    difficulty: 3,
    color: "#7890c8",
    summary: "Spear fighter that controls bridges, entrances, villages, and objective zones with defensive lines.",
    strengths: ["Bridge control", "High defense", "Strong anti-dive tools"],
    weaknesses: ["Lower burst", "Limited mobility", "Needs positional discipline"],
    tags: ["Control", "Defense", "Spear"],
    stats: {
      health: 178,
      moveSpeed: 232,
      damageBonus: 4,
      defense: 0.12,
      range: 3,
      mobility: 2,
      utility: 4,
      baseSupport: 3,
      objectiveControl: 5
    },
    bars: { Health: 4, Damage: 3, Range: 3, Mobility: 2, Defense: 5, Utility: 4, "Base Support": 3, "Objective Control": 5, Difficulty: 3 },
    abilities: {
      basic: {
        id: "basic",
        label: "Spear Thrust",
        input: "Mouse 1",
        type: "melee",
        cooldown: 0.58,
        damage: 19,
        range: 132,
        radius: 28,
        color: "#9bb0ff",
        description: "A narrow forward spear thrust with slightly longer melee reach."
      },
      skillshot: {
        id: "skillshot",
        label: "Javelin Throw",
        input: "Q",
        type: "projectile",
        cooldown: 4.8,
        damage: 35,
        range: 650,
        speed: 820,
        radius: 7,
        color: "#d8c59a",
        status: { slow: 0.36, duration: 1.35 },
        description: "Throws a javelin that damages and slows the first enemy hit."
      },
      area: {
        id: "area",
        label: "Phalanx Wall",
        input: "E",
        type: "flameWall",
        cooldown: 13.5,
        damage: 5,
        range: 160,
        radius: 24,
        wallLength: 270,
        wallWidth: 46,
        duration: 4.4,
        tickRate: 0.75,
        color: "#7890c8",
        status: { slow: 0.42, duration: 1.1 },
        damageReduction: 0.18,
        description: "Places a short defensive spear line that slows enemies crossing it."
      },
      ultimate: {
        id: "ultimate",
        label: "Impaling Circle",
        input: "R",
        type: "area",
        cooldown: 39,
        damage: 74,
        range: 430,
        radius: 178,
        duration: 0.65,
        color: "#9bb0ff",
        status: { slow: 0.48, duration: 2.1 },
        description: "Creates a circular spear zone that damages and slows enemies inside."
      }
    }
  },
  warlock: {
    id: "warlock",
    label: "Warlock",
    shortLabel: "WRL",
    role: "Damage-over-time / curses / summons",
    difficulty: 4,
    color: "#8d5ab8",
    summary: "Dark caster that curses enemies, harvests souls, summons imps, and scales into longer fights.",
    strengths: ["Strong scaling", "Damage over time", "Summon pressure"],
    weaknesses: ["Fragile", "Low mobility", "Needs souls and setup"],
    tags: ["Caster", "Debuff", "Scaling"],
    stats: {
      health: 132,
      moveSpeed: 232,
      damageBonus: 5,
      defense: 0.01,
      range: 4,
      mobility: 1,
      utility: 5,
      baseSupport: 1,
      objectiveControl: 5
    },
    bars: { Health: 2, Damage: 5, Range: 4, Mobility: 1, Defense: 1, Utility: 5, "Base Support": 1, "Objective Control": 5, Difficulty: 4 },
    abilities: {
      basic: {
        id: "basic",
        label: "Shadow Bolt",
        input: "Mouse 1",
        type: "projectile",
        cooldown: 0.66,
        damage: 17,
        range: 535,
        speed: 650,
        radius: 7,
        color: "#b391f0",
        description: "Fires a dark projectile at medium range."
      },
      skillshot: {
        id: "skillshot",
        label: "Soul Curse",
        input: "Q",
        type: "projectile",
        cooldown: 5.7,
        damage: 24,
        range: 660,
        speed: 760,
        radius: 8,
        color: "#8d5ab8",
        status: { curse: 4.2, curseDamagePerSecond: 6, slow: 0.18, duration: 1.8 },
        description: "Curses the first enemy hit, applying damage over time and a brief slow."
      },
      area: {
        id: "area",
        label: "Summon Imp",
        input: "E",
        type: "summon",
        cooldown: 15,
        damage: 13,
        range: 380,
        radius: 18,
        duration: 13,
        summonKind: "imp",
        summonHealth: 92,
        color: "#b391f0",
        description: "Summons a fragile imp that attacks nearby enemies."
      },
      ultimate: {
        id: "ultimate",
        label: "Soul Rift",
        input: "R",
        type: "area",
        cooldown: 46,
        damage: 46,
        range: 650,
        radius: 230,
        duration: 3.2,
        tickRate: 0.65,
        color: "#7c63c7",
        status: { slow: 0.38, duration: 1.35 },
        description: "Opens a dark rift that repeatedly damages and slows enemies in the zone."
      }
    }
  }
});

export const CHARACTER_CLASS_IDS = Object.freeze(Object.keys(CHARACTER_CLASSES));

export function getCharacterClass(id = "ranger") {
  return CHARACTER_CLASSES[id] || CHARACTER_CLASSES.ranger;
}

export function randomCharacterClassId(exclude = null) {
  const pool = CHARACTER_CLASS_IDS.filter((id) => id !== exclude);
  return pool[Math.floor(Math.random() * pool.length)] || "ranger";
}







